//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticRescouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticRescouces.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết không được rỗng.
        /// </summary>
        public static string baivietkhongduocrong {
            get {
                return ResourceManager.GetString("baivietkhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa bản ghi này không?.
        /// </summary>
        public static string bancomuonbangghinaykhong {
            get {
                return ResourceManager.GetString("bancomuonbangghinaykhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật danh mục.
        /// </summary>
        public static string capnhatdanhluc {
            get {
                return ResourceManager.GetString("capnhatdanhluc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa danh mục sản phẩm.
        /// </summary>
        public static string chinhsuadanhmucsanpham {
            get {
                return ResourceManager.GetString("chinhsuadanhmucsanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tệp.
        /// </summary>
        public static string chontep {
            get {
                return ResourceManager.GetString("chontep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục loại sản phẩm.
        /// </summary>
        public static string danhmucloaisanpham {
            get {
                return ResourceManager.GetString("danhmucloaisanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        public static string danhsachsanpham {
            get {
                return ResourceManager.GetString("danhsachsanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin tức.
        /// </summary>
        public static string danhsachtintuc {
            get {
                return ResourceManager.GetString("danhsachtintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string hienthi {
            get {
                return ResourceManager.GetString("hienthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string hinhanh {
            get {
                return ResourceManager.GetString("hinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh không được rỗng.
        /// </summary>
        public static string hinhanhkhongduocrong {
            get {
                return ResourceManager.GetString("hinhanhkhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu tượng(icon).
        /// </summary>
        public static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào.
        /// </summary>
        public static string khongcobanghi {
            get {
                return ResourceManager.GetString("khongcobanghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string luu {
            get {
                return ResourceManager.GetString("luu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string mota {
            get {
                return ResourceManager.GetString("mota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string ngaytao {
            get {
                return ResourceManager.GetString("ngaytao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập.
        /// </summary>
        public static string nhap {
            get {
                return ResourceManager.GetString("nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục.
        /// </summary>
        public static string quanlydanhmuc {
            get {
                return ResourceManager.GetString("quanlydanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay Lại.
        /// </summary>
        public static string quaylai {
            get {
                return ResourceManager.GetString("quaylai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string stt {
            get {
                return ResourceManager.GetString("stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string sua {
            get {
                return ResourceManager.GetString("sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa tin tức.
        /// </summary>
        public static string suatintuc {
            get {
                return ResourceManager.GetString("suatintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải ảnh.
        /// </summary>
        public static string taianh {
            get {
                return ResourceManager.GetString("taianh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải tệp mẫu.
        /// </summary>
        public static string taitep {
            get {
                return ResourceManager.GetString("taitep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tin tức.
        /// </summary>
        public static string taotintuc {
            get {
                return ResourceManager.GetString("taotintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string tendanhmuc {
            get {
                return ResourceManager.GetString("tendanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục không để trống.
        /// </summary>
        public static string tendanhmuckhongdcrong {
            get {
                return ResourceManager.GetString("tendanhmuckhongdcrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại.
        /// </summary>
        public static string tenloai {
            get {
                return ResourceManager.GetString("tenloai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string thanhcong {
            get {
                return ResourceManager.GetString("thanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm danh mục không thành công.
        /// </summary>
        public static string themdanhmuckhongthanhcong {
            get {
                return ResourceManager.GetString("themdanhmuckhongthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm danh mục thành công.
        /// </summary>
        public static string themdanhmucthanhcon {
            get {
                return ResourceManager.GetString("themdanhmucthanhcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string themmoi {
            get {
                return ResourceManager.GetString("themmoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới danh mục sản phẩm.
        /// </summary>
        public static string themmoiloaisanpham {
            get {
                return ResourceManager.GetString("themmoiloaisanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chỉnh sửa tin tức.
        /// </summary>
        public static string thongitnchinhsuatintuc {
            get {
                return ResourceManager.GetString("thongitnchinhsuatintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chỉnh sửa loại danh mục.
        /// </summary>
        public static string thongtinchinhsualoaidanhmuc {
            get {
                return ResourceManager.GetString("thongtinchinhsualoaidanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin danh mục.
        /// </summary>
        public static string Thongtindanhmuc {
            get {
                return ResourceManager.GetString("Thongtindanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thêm mới danh mục.
        /// </summary>
        public static string thongtinthemmoiloaisanpham {
            get {
                return ResourceManager.GetString("thongtinthemmoiloaisanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thêm mới tin tức.
        /// </summary>
        public static string thongtintintuc {
            get {
                return ResourceManager.GetString("thongtintintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string thutu {
            get {
                return ResourceManager.GetString("thutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự không được rỗng.
        /// </summary>
        public static string thutukhongdcrong {
            get {
                return ResourceManager.GetString("thutukhongdcrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietNamese.
        /// </summary>
        public static string tiengadmin {
            get {
                return ResourceManager.GetString("tiengadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string tieude {
            get {
                return ResourceManager.GetString("tieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề không được rỗng.
        /// </summary>
        public static string tieudekhongduocrong {
            get {
                return ResourceManager.GetString("tieudekhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string timkiem {
            get {
                return ResourceManager.GetString("timkiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string trang {
            get {
                return ResourceManager.GetString("trang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string trangthai {
            get {
                return ResourceManager.GetString("trangthai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        public static string VietNamese {
            get {
                return ResourceManager.GetString("VietNamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string xoa {
            get {
                return ResourceManager.GetString("xoa", resourceCulture);
            }
        }
    }
}
