//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticRescouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticRescouces.ResourceUser", typeof(ResourceUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn vào đây để đăng nhập.
        /// </summary>
        public static string anvaodaydedangnhap {
            get {
                return ResourceManager.GetString("anvaodaydedangnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ấn.
        /// </summary>
        public static string apdung {
            get {
                return ResourceManager.GetString("apdung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài đăng thường xuyên.
        /// </summary>
        public static string BaiDangThuongXuyen {
            get {
                return ResourceManager.GetString("BaiDangThuongXuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string baiviet {
            get {
                return ResourceManager.GetString("baiviet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết mới nhất.
        /// </summary>
        public static string baivietmoinhat {
            get {
                return ResourceManager.GetString("baivietmoinhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết về sản phẩm.
        /// </summary>
        public static string Baivietvesanpham {
            get {
                return ResourceManager.GetString("Baivietvesanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bấm vào đây để nhập mã của bạn.
        /// </summary>
        public static string bamvaodaydenhapmacuaban {
            get {
                return ResourceManager.GetString("bamvaodaydenhapmacuaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang tìm kiếm cái gì.
        /// </summary>
        public static string BanDangTimKiemCaiGi {
            get {
                return ResourceManager.GetString("BanDangTimKiemCaiGi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá sản phẩm.
        /// </summary>
        public static string binhluan {
            get {
                return ResourceManager.GetString("binhluan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các danh mục.
        /// </summary>
        public static string CacLoaiDanhMuc {
            get {
                return ResourceManager.GetString("CacLoaiDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm.
        /// </summary>
        public static string Cacsanpham {
            get {
                return ResourceManager.GetString("Cacsanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm của chúng tôi.
        /// </summary>
        public static string Cacsanphamcuachungtoi {
            get {
                return ResourceManager.GetString("Cacsanphamcuachungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm mới về.
        /// </summary>
        public static string Cacsanphammoive {
            get {
                return ResourceManager.GetString("Cacsanphammoive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tất cả sản phẩm.
        /// </summary>
        public static string Capnhattatcasanpham {
            get {
                return ResourceManager.GetString("Capnhattatcasanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi thường gặp.
        /// </summary>
        public static string cauhoithuonggap {
            get {
                return ResourceManager.GetString("cauhoithuonggap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng đến website của chúng tôi.
        /// </summary>
        public static string chaomungdenwebcuachungtoi {
            get {
                return ResourceManager.GetString("chaomungdenwebcuachungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấp nhận cho.
        /// </summary>
        public static string ChapNhancho {
            get {
                return ResourceManager.GetString("ChapNhancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ.
        /// </summary>
        public static string chiase {
            get {
                return ResourceManager.GetString("chiase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách hoàn trả 24 giờ.
        /// </summary>
        public static string Chinhsach {
            get {
                return ResourceManager.GetString("Chinhsach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách bảo mật.
        /// </summary>
        public static string chinhsachbaomat {
            get {
                return ResourceManager.GetString("chinhsachbaomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách hoàn trả 24 giờ.
        /// </summary>
        public static string chinhsachhoantra24gio {
            get {
                return ResourceManager.GetString("chinhsachhoantra24gio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết tài khoản.
        /// </summary>
        public static string chitiettaikhoan {
            get {
                return ResourceManager.GetString("chitiettaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi rất mong nhận được hồi âm từ bạn.
        /// </summary>
        public static string chungtoiratmongnhanduochoiamtuban {
            get {
                return ResourceManager.GetString("chungtoiratmongnhanduochoiamtuban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ nhật: 10am - 6pm.
        /// </summary>
        public static string chunhat {
            get {
                return ResourceManager.GetString("chunhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển khoản qua VNPAY.
        /// </summary>
        public static string chuyenkhoanquavnpay {
            get {
                return ResourceManager.GetString("chuyenkhoanquavnpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có phiếu giảm giá.
        /// </summary>
        public static string cohieusamgia {
            get {
                return ResourceManager.GetString("cohieusamgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Models.Common.Common.FormatNumber(item.Price, 0).
        /// </summary>
        public static string ConverTien {
            get {
                return ResourceManager.GetString("ConverTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to của.
        /// </summary>
        public static string cua {
            get {
                return ResourceManager.GetString("cua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng của chúng tôi.
        /// </summary>
        public static string cuahangcuachungtoi {
            get {
                return ResourceManager.GetString("cuahangcuachungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đảm bảo 100% về sản phẩm.
        /// </summary>
        public static string Dambao {
            get {
                return ResourceManager.GetString("Dambao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đảm bảo lại tiền.
        /// </summary>
        public static string Dambaolaitien {
            get {
                return ResourceManager.GetString("Dambaolaitien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string DangKy {
            get {
                return ResourceManager.GetString("DangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký nhận mã giảm giá.
        /// </summary>
        public static string DangKyNhanMaGiamGia {
            get {
                return ResourceManager.GetString("DangKyNhanMaGiamGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string dangkytaikhoan {
            get {
                return ResourceManager.GetString("dangkytaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string dangnhap {
            get {
                return ResourceManager.GetString("dangnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập/ Đăng ký.
        /// </summary>
        public static string DangNhapDangky {
            get {
                return ResourceManager.GetString("DangNhapDangky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá của bạn.
        /// </summary>
        public static string danhgiacuaban {
            get {
                return ResourceManager.GetString("danhgiacuaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá sản phẩm.
        /// </summary>
        public static string danhgiasanpham {
            get {
                return ResourceManager.GetString("danhgiasanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string DanhMuc {
            get {
                return ResourceManager.GetString("DanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string dathang {
            get {
                return ResourceManager.GetString("dathang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string diachi {
            get {
                return ResourceManager.GetString("diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email của bạn sẽ không được công bố. Các trường bắt buộc được đánh dấu.
        /// </summary>
        public static string diachiemailcuabansekhongduoccongbo {
            get {
                return ResourceManager.GetString("diachiemailcuabansekhongduoccongbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ giao hàng.
        /// </summary>
        public static string diachigiaohang {
            get {
                return ResourceManager.GetString("diachigiaohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ thanh toán.
        /// </summary>
        public static string diachihanhtoan {
            get {
                return ResourceManager.GetString("diachihanhtoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được rỗng.
        /// </summary>
        public static string diachikhongduocrong {
            get {
                return ResourceManager.GetString("diachikhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ người dùng.
        /// </summary>
        public static string diachinguoidung {
            get {
                return ResourceManager.GetString("diachinguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa phương.
        /// </summary>
        public static string diaphuong {
            get {
                return ResourceManager.GetString("diaphuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ chất lượng.
        /// </summary>
        public static string Dichvuchatluong {
            get {
                return ResourceManager.GetString("Dichvuchatluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền code.
        /// </summary>
        public static string diencode {
            get {
                return ResourceManager.GetString("diencode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản sử dụng.
        /// </summary>
        public static string dieukhoansudung {
            get {
                return ResourceManager.GetString("dieukhoansudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc thêm.
        /// </summary>
        public static string docnhieu {
            get {
                return ResourceManager.GetString("docnhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc thêm.
        /// </summary>
        public static string Docthem {
            get {
                return ResourceManager.GetString("Docthem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn.
        /// </summary>
        public static string donhangcuaban {
            get {
                return ResourceManager.GetString("donhangcuaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được rỗng.
        /// </summary>
        public static string emailkhongduocrong {
            get {
                return ResourceManager.GetString("emailkhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú(tùy chọn).
        /// </summary>
        public static string ghichu {
            get {
                return ResourceManager.GetString("ghichu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Gia {
            get {
                return ResourceManager.GetString("Gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm.
        /// </summary>
        public static string Giam {
            get {
                return ResourceManager.GetString("Giam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá 30% Mã sử dụng.
        /// </summary>
        public static string Giamgia30masudung {
            get {
                return ResourceManager.GetString("Giamgia30masudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng nhanh chóng và an toàn.
        /// </summary>
        public static string Giaohang {
            get {
                return ResourceManager.GetString("Giaohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng miễn phí.
        /// </summary>
        public static string Giaohangmienphi {
            get {
                return ResourceManager.GetString("Giaohangmienphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng &amp; nhanh chóng và an toàn.
        /// </summary>
        public static string GiaoHangNhanhChongAnToan {
            get {
                return ResourceManager.GetString("GiaoHangNhanhChongAnToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string Giohang {
            get {
                return ResourceManager.GetString("Giohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ mở cửa.
        /// </summary>
        public static string giomocua {
            get {
                return ResourceManager.GetString("giomocua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi bình luận.
        /// </summary>
        public static string guibinhluan {
            get {
                return ResourceManager.GetString("guibinhluan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi phản hồi.
        /// </summary>
        public static string guiphanhoi {
            get {
                return ResourceManager.GetString("guiphanhoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng Khuyến mãi.
        /// </summary>
        public static string HangKhuyenmai {
            get {
                return ResourceManager.GetString("HangKhuyenmai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng mới.
        /// </summary>
        public static string HangMoi {
            get {
                return ResourceManager.GetString("HangMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy kể về dịch vụ của bạn..
        /// </summary>
        public static string HayKeVedichvucuaban {
            get {
                return ResourceManager.GetString("HayKeVedichvucuaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện.
        /// </summary>
        public static string Hien {
            get {
                return ResourceManager.GetString("Hien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string Homnay {
            get {
                return ResourceManager.GetString("Homnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm qua.
        /// </summary>
        public static string Homqua {
            get {
                return ResourceManager.GetString("Homqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ.
        /// </summary>
        public static string Hotro {
            get {
                return ResourceManager.GetString("Hotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ chất lượng chuyên nghiệp.
        /// </summary>
        public static string hotrochatluongchuyennghiep {
            get {
                return ResourceManager.GetString("hotrochatluongchuyennghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ phục vụ 24/7..
        /// </summary>
        public static string hotrophucvu {
            get {
                return ResourceManager.GetString("hotrophucvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string hovaten {
            get {
                return ResourceManager.GetString("hovaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được rỗng.
        /// </summary>
        public static string hovatenkhongduocrong {
            get {
                return ResourceManager.GetString("hovatenkhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        public static string Ketqua {
            get {
                return ResourceManager.GetString("Ketqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string Ketquatimkiem {
            get {
                return ResourceManager.GetString("Ketquatimkiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá tất cả sản phẩm.
        /// </summary>
        public static string Khamphatatcasanpham {
            get {
                return ResourceManager.GetString("Khamphatatcasanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục mặc định.
        /// </summary>
        public static string Khoiphucmacdinh {
            get {
                return ResourceManager.GetString("Khoiphucmacdinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có câu hỏi hỏi..
        /// </summary>
        public static string khongcocauhoi {
            get {
                return ResourceManager.GetString("khongcocauhoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sản phẩm trong giỏ hàng.
        /// </summary>
        public static string khongcosanphamtrongigohang {
            get {
                return ResourceManager.GetString("khongcosanphamtrongigohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string lienhe {
            get {
                return ResourceManager.GetString("lienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết nhanh.
        /// </summary>
        public static string lienketnhanh {
            get {
                return ResourceManager.GetString("lienketnhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string lienvoichungtoi {
            get {
                return ResourceManager.GetString("lienvoichungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        public static string Loc {
            get {
                return ResourceManager.GetString("Loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xem.
        /// </summary>
        public static string Luotxem {
            get {
                return ResourceManager.GetString("Luotxem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định.
        /// </summary>
        public static string Macdinh {
            get {
                return ResourceManager.GetString("Macdinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định phân loại.
        /// </summary>
        public static string Macdinhphanloai {
            get {
                return ResourceManager.GetString("Macdinhphanloai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền mật khẩu.
        /// </summary>
        public static string matkhau {
            get {
                return ResourceManager.GetString("matkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được rỗng.
        /// </summary>
        public static string matkhaukhongduocrong {
            get {
                return ResourceManager.GetString("matkhaukhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string matkhaumoi {
            get {
                return ResourceManager.GetString("matkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải ít nhất 6 kí tự..
        /// </summary>
        public static string matkhauphaiitnhat {
            get {
                return ResourceManager.GetString("matkhauphaiitnhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu và mật khẩu xác nhận không khớp..
        /// </summary>
        public static string matkhauvamatkhaukhongkhop {
            get {
                return ResourceManager.GetString("matkhauvamatkhaukhongkhop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí.
        /// </summary>
        public static string mienphi {
            get {
                return ResourceManager.GetString("mienphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí vận chuyển.
        /// </summary>
        public static string mienphivanchuyen {
            get {
                return ResourceManager.GetString("mienphivanchuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi quyền được bảo lưu bởi.
        /// </summary>
        public static string moiquyenduocbaoluuboi {
            get {
                return ResourceManager.GetString("moiquyenduocbaoluuboi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Mota {
            get {
                return ResourceManager.GetString("Mota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả của bạn.
        /// </summary>
        public static string motacuaban {
            get {
                return ResourceManager.GetString("motacuaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua Ngay.
        /// </summary>
        public static string MuaNgay {
            get {
                return ResourceManager.GetString("MuaNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua sản phẩm này.
        /// </summary>
        public static string MuaSanphamnay {
            get {
                return ResourceManager.GetString("MuaSanphamnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn chưa đăng nhập, vui lòng đăng nhập trước.
        /// </summary>
        public static string neubanchuadangnhapvuilongdangnhaptruoc {
            get {
                return ResourceManager.GetString("neubanchuadangnhapvuilongdangnhaptruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn có mã giảm giá, vui lòng áp dụng nó bên dưới..
        /// </summary>
        public static string neubancomagiamgia {
            get {
                return ResourceManager.GetString("neubancomagiamgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn có những sản phẩm tuyệt vời mà bạn đang tạo ra hoặc muốn hợp tác với chúng tôi thì hãy liên hệ với chúng tôi.
        /// </summary>
        public static string neubanconhungsanpham {
            get {
                return ResourceManager.GetString("neubanconhungsanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin tức.
        /// </summary>
        public static string newlist {
            get {
                return ResourceManager.GetString("newlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã phiếu giảm giá.
        /// </summary>
        public static string Nhapcode {
            get {
                return ResourceManager.GetString("Nhapcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string nhaplaimatkhau {
            get {
                return ResourceManager.GetString("nhaplaimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu không được rỗng.
        /// </summary>
        public static string nhaplaimatkhaukhongduocrong {
            get {
                return ResourceManager.GetString("nhaplaimatkhaukhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mat khau moi.
        /// </summary>
        public static string nhaplaimatkhaumoi {
            get {
                return ResourceManager.GetString("nhaplaimatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tài khoản....
        /// </summary>
        public static string nhaptaikhoan {
            get {
                return ResourceManager.GetString("nhaptaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ mật khẩu.
        /// </summary>
        public static string nhotoi {
            get {
                return ResourceManager.GetString("nhotoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải đúng định dạng email.
        /// </summary>
        public static string Phaidungdinhdangemail {
            get {
                return ResourceManager.GetString("Phaidungdinhdangemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi khách hàng?.
        /// </summary>
        public static string phanhoikhachhang {
            get {
                return ResourceManager.GetString("phanhoikhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí vận chuyển.
        /// </summary>
        public static string phivanchuyen {
            get {
                return ResourceManager.GetString("phivanchuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan tâm.
        /// </summary>
        public static string quantam {
            get {
                return ResourceManager.GetString("quantam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string quenmatkhau {
            get {
                return ResourceManager.GetString("quenmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string quenmetkhau {
            get {
                return ResourceManager.GetString("quenmetkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình thanh toán.
        /// </summary>
        public static string Quytrinhthanhtoan {
            get {
                return ResourceManager.GetString("Quytrinhthanhtoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string sanpham {
            get {
                return ResourceManager.GetString("sanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm bán chạy nhất.
        /// </summary>
        public static string SanPhamBanChayNhat {
            get {
                return ResourceManager.GetString("SanPhamBanChayNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chất lượng.
        /// </summary>
        public static string SanPhamChatLuong {
            get {
                return ResourceManager.GetString("SanPhamChatLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chính hãng.
        /// </summary>
        public static string Sanphamchinhhang {
            get {
                return ResourceManager.GetString("Sanphamchinhhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm liên quan.
        /// </summary>
        public static string Sanphamlienquan {
            get {
                return ResourceManager.GetString("Sanphamlienquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm đã xem gần đây.
        /// </summary>
        public static string sanphamxemganday {
            get {
                return ResourceManager.GetString("sanphamxemganday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm yêu thích.
        /// </summary>
        public static string Sanphamyeuthich {
            get {
                return ResourceManager.GetString("Sanphamyeuthich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string sodienthoai {
            get {
                return ResourceManager.GetString("sodienthoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string soluong {
            get {
                return ResourceManager.GetString("soluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to số lượng sản phẩm còn lại ở trong kho.
        /// </summary>
        public static string soluongsanphamconlai {
            get {
                return ResourceManager.GetString("soluongsanphamconlai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượt xem của khách hàng.
        /// </summary>
        public static string Soluotxemcuakhachhang {
            get {
                return ResourceManager.GetString("Soluotxemcuakhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số người Online.
        /// </summary>
        public static string Songuoionline {
            get {
                return ResourceManager.GetString("Songuoionline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi hiểu rồi, mọi thứ sẽ xảy ra. Chỉ cần nhập địa chỉ email của bạn dưới đây
        ///và chúng tôi sẽ gửi cho bạn một liên kết để đặt lại mật khẩu của bạn!.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ dashboard tài khoản của bạn, bạn có thể xem các đơn đặt hàng gần đây, quản lý địa chỉ giao hàng và thanh toán cũng như chỉnh sửa mật khẩu và chi tiết tài khoản của mình..
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các địa chỉ sau sẽ được sử dụng trên trang thanh toán theo mặc định..
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các địa chỉ sau sẽ được sử dụng trên trang thanh toán theo mặc định.
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ email.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email của bạn đã được gửi thành công!.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra email của bạn để đặt lại mật khẩu..
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về trang chủ.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về trang đăng nhập.
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản?.
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tại đây!.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Stt {
            get {
                return ResourceManager.GetString("Stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải App.
        /// </summary>
        public static string Taiapp {
            get {
                return ResourceManager.GetString("Taiapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string TaiKhoan {
            get {
                return ResourceManager.GetString("TaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của tôi.
        /// </summary>
        public static string TaiKhoancuatoi {
            get {
                return ResourceManager.GetString("TaiKhoancuatoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không hợp lệ.
        /// </summary>
        public static string taikhoanhoacmatkhaukhonghople {
            get {
                return ResourceManager.GetString("taikhoanhoacmatkhaukhonghople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không được rỗng.
        /// </summary>
        public static string taikhoankhongduocrong {
            get {
                return ResourceManager.GetString("taikhoankhongduocrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng.
        /// </summary>
        public static string taikhoannguoidung {
            get {
                return ResourceManager.GetString("taikhoannguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm phí.
        /// </summary>
        public static string tamphi {
            get {
                return ResourceManager.GetString("tamphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm tính.
        /// </summary>
        public static string tamtinh {
            get {
                return ResourceManager.GetString("tamtinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo một tài khoản!.
        /// </summary>
        public static string taotaikhoan {
            get {
                return ResourceManager.GetString("taotaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản!.
        /// </summary>
        public static string taotaikhoandangky {
            get {
                return ResourceManager.GetString("taotaikhoandangky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string TatCa {
            get {
                return ResourceManager.GetString("TatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả sản phẩm.
        /// </summary>
        public static string tatcasanpham {
            get {
                return ResourceManager.GetString("tatcasanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string tenkhachhnag {
            get {
                return ResourceManager.GetString("tenkhachhnag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string tensanpham {
            get {
                return ResourceManager.GetString("tensanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán bằng tiền mặt khi giao hàng..
        /// </summary>
        public static string thanhtoanbangtienmat {
            get {
                return ResourceManager.GetString("thanhtoanbangtienmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán khi giao hàng.
        /// </summary>
        public static string thanhtoankhigiaohang {
            get {
                return ResourceManager.GetString("thanhtoankhigiaohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán online qua Paypal.
        /// </summary>
        public static string thanhtoanonlinequapaypal {
            get {
                return ResourceManager.GetString("thanhtoanonlinequapaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua PayPal; bạn có thể thanh toán bằng thẻ tín dụng nếu bạn không có tài khoản PayPal.
        /// </summary>
        public static string thanhtoanquapaypal {
            get {
                return ResourceManager.GetString("thanhtoanquapaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên website bán linh kiện DV Computer kể từ ngày.
        /// </summary>
        public static string thanhvien {
            get {
                return ResourceManager.GetString("thanhvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay vì mua sáu thứ, hãy mua một thứ mà bạn thực sự thích.
        /// </summary>
        public static string thayvimuathu {
            get {
                return ResourceManager.GetString("thayvimuathu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng.
        /// </summary>
        public static string ThemGioHang {
            get {
                return ResourceManager.GetString("ThemGioHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string Thongtinchitiet {
            get {
                return ResourceManager.GetString("Thongtinchitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng.
        /// </summary>
        public static string thongtinnguoidung {
            get {
                return ResourceManager.GetString("thongtinnguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhận hàng.
        /// </summary>
        public static string thongtinnhanhang {
            get {
                return ResourceManager.GetString("thongtinnhanhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tất cả người dùng.
        /// </summary>
        public static string thongtintatcanguoidung {
            get {
                return ResourceManager.GetString("thongtintatcanguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ Hai đến Thứ Bảy: 9am - 10pm.
        /// </summary>
        public static string thu2denchu7 {
            get {
                return ResourceManager.GetString("thu2denchu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#8363;.
        /// </summary>
        public static string Tien {
            get {
                return ResourceManager.GetString("Tien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiết kiệm $3 chỉ với ứng dụng và người dùng mới.
        /// </summary>
        public static string Tietkiem3chivoiungdungvanguoidungmoi {
            get {
                return ResourceManager.GetString("Tietkiem3chivoiungdungvanguoidungmoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm sản phẩm.
        /// </summary>
        public static string TimKiemSanPham {
            get {
                return ResourceManager.GetString("TimKiemSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn của bạn.
        /// </summary>
        public static string tinnhancuaban {
            get {
                return ResourceManager.GetString("tinnhancuaban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string tintuc {
            get {
                return ResourceManager.GetString("tintuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức xem gần đây.
        /// </summary>
        public static string tintucxemganday {
            get {
                return ResourceManager.GetString("tintucxemganday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        public static string tong {
            get {
                return ResourceManager.GetString("tong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng phụ.
        /// </summary>
        public static string tongphu {
            get {
                return ResourceManager.GetString("tongphu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng quan đơn hàng.
        /// </summary>
        public static string tongquandonhang {
            get {
                return ResourceManager.GetString("tongquandonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại dễ dàng.
        /// </summary>
        public static string Tralaidedang {
            get {
                return ResourceManager.GetString("Tralaidedang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Trangchu {
            get {
                return ResourceManager.GetString("Trangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong tháng này.
        /// </summary>
        public static string TrongThangNay {
            get {
                return ResourceManager.GetString("TrongThangNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong tuần này.
        /// </summary>
        public static string TrongTuanNay {
            get {
                return ResourceManager.GetString("TrongTuanNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong vòng 10 ngày..
        /// </summary>
        public static string Trongvonggay {
            get {
                return ResourceManager.GetString("Trongvonggay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần này.
        /// </summary>
        public static string Tuannay {
            get {
                return ResourceManager.GetString("Tuannay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ giá cố định.
        /// </summary>
        public static string tygiacodinh {
            get {
                return ResourceManager.GetString("tygiacodinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền tài khoản.
        /// </summary>
        public static string usernmaeenter {
            get {
                return ResourceManager.GetString("usernmaeenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        public static string VietNamese {
            get {
                return ResourceManager.GetString("VietNamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website bán linh kiện máy tính DV Computer.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string Xem {
            get {
                return ResourceManager.GetString("Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string Xemchitiet {
            get {
                return ResourceManager.GetString("Xemchitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem sản phẩm yêu thích.
        /// </summary>
        public static string xemsanphamyeuthich {
            get {
                return ResourceManager.GetString("xemsanphamyeuthich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả các sản phẩm.
        /// </summary>
        public static string XemTatCa {
            get {
                return ResourceManager.GetString("XemTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả các sản phẩm.
        /// </summary>
        public static string Xemtatcacacsanpham {
            get {
                return ResourceManager.GetString("Xemtatcacacsanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin Chào.
        /// </summary>
        public static string xinchao {
            get {
                return ResourceManager.GetString("xinchao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tất cả sản phẩm trong giỏ hàng.
        /// </summary>
        public static string Xoatatcasanphamtronggiohang {
            get {
                return ResourceManager.GetString("Xoatatcasanphamtronggiohang", resourceCulture);
            }
        }
    }
}
